# Generated by Django 3.0.7 on 2020-06-24 08:23

from django.db import migrations, models
import tweets.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20200610_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.CharField(default='Nil', max_length=140, validators=[tweets.validators.validate_content]),
        ),
    ]
